### ISSUE TITLE
Setup with xcworkspace is not working if xcodeproj is in a different folder

### ISSUE THREAD

**Issue by siimon** [wojciech-kulik/xcodebuild.nvim#1]
First I just want to thanks for this great plugin + an awesome blogpost.. I've been missing vim quite alot in my daily job and would love to use it more with iOS development.

On to my issue, I seem to have problem running setup in some projects I have and I've pinned it down to the structure of the project. The folder structure of the project looks something like this
```
-- root
  -- MyApp.xcworkspace
  -- MyApp
    -- MyApp.xcodeproj
```
This unfortunately breaks the assumption in `get_project_information` that the xcworkspace and the xcodeproj is in the same folder. What do you think would be the best solution to fix this?

**Comment by wojciech-kulik** [comment]
Thank you very much! 
Hmm, interesting case. I think that the best solution would be to split project selection into 2 steps: 
1. Select xcworkspace (optional, only if we detect xcworkspace, if not we skip second point and show xcodeproj picker)
2. Check if xcodeproj exists in the same location with the same name, if not show xcodeproj picker.

This solution would have to take into consideration current users that didn't have this step.
Maybe we could check it in "get_project_information" and show picker if needed (only if xcodeproj doesn't exist where we expect it).

Would you like to implement those changes or do you want to wait for me to do that?

**Comment by wojciech-kulik** [comment]
@siimon this issue should be fixed now. Could you update the plugin and see if it works as expected now?

**Comment by siimon** [comment]
@wojciech-kulik works perfectly, thank you so much!
