### ISSUE TITLE
No schemes found on v3.3.0

### ISSUE THREAD

**Issue by dudek-j** [wojciech-kulik/xcodebuild.nvim#104]
## Steps to recreate
- Create new empty project
- Run `xcode-build-server`
- Open nvim and run `XcodebuildSetup`
---
Works as expected when i drop down to v3.2.0.
`checkhealth` shows all green.
Running on `macOS 13.6` with `xcodebuild 15.1`

**Comment by wojciech-kulik** [comment]
Hi! Thanks for reporting this issue. 

Could you switch to this branch and try it again?
https://github.com/wojciech-kulik/xcodebuild.nvim/pull/105

**Comment by dudek-j** [comment]
Works as expected on 3cf482508b5d0562b36b16c782f0fdfb8a95e298 🥳
