### ISSUE TITLE
Installing a tvOS app doesn't work

### ISSUE THREAD

**Issue by darkwater** [wojciech-kulik/xcodebuild.nvim#118]
1. Open Xcode and create a new project
2. Select tvOS app and all of the default options (SwiftUI etc.)
3. Close Xcode and open the project in nvim
4. XcodebuildSetup, XcodebuildBootSimulator, XcodebuildBuildRun

Following these steps leads to a `Could not install app (code: 2)` after a short build. If I create an iOS project instead, it installs and runs just fine. If I select a real Apple TV device instead of the simulator, I get code 148 instead. (Is there a list of what these codes mean somewhere, or are they opaque Apple codes?)

**Comment by wojciech-kulik** [comment]
Hi, it wasn't supported. I've just added support for all platforms. Please check it and let me know if it works now :).

**Comment by darkwater** [comment]
Yep, works perfectly now
