### ISSUE TITLE
How can I enable macros?

### ISSUE THREAD

**Issue by agarrharr** [wojciech-kulik/xcodebuild.nvim#124]
When I build, I get the following errors because of macros and I'm not sure how to build the project with this plugin.

```
  1 -----------------------------
  2 -- xcodebuild.nvim summary --
  3 -----------------------------
  4
  5 Errors:
  6   ✖ Target 'ComposableArchitectureMacros' must be enabled before it can be used.
  7   ✖ Target 'CasePathsMacros' must be enabled before it can be used.
  8   ✖ Target 'DependenciesMacrosPlugin' must be enabled before it can be used.
  9   ✖ Target 'PerceptionMacros' must be enabled before it can be used.
 10
 11   Build Failed
 12
```

 In Xcode, I can click on each of them and enable them. And for Xcode Cloud, I have the following script (`ci_scripts/ci_pre_xcodebuld.sh`).
 
```
#!/bin/sh

defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
```

Is there a way to enable the macros? Or is there a way to skip macro validation?

**Comment by wojciech-kulik** [comment]
I'm not very familiar with macros, but you can try passing extra argument to `xcodebuild` (plugin options have a field to provide it).

Also, If it works for you on Xcode Cloud, it should work with the plugin as well. Have you tried running this command before starting build?

**Comment by agarrharr** [comment]
Yes, running `:!defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES` in command mode, followed by `:XcodebuildBuild` worked.

What is the plugin option where I can provide extra arguments to `xcodebuild`?

**Comment by wojciech-kulik** [comment]
<img width="778" alt="image" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/3128467/b9474788-d940-46c0-9a1b-262299270b25">

`extra_*`
