### ISSUE TITLE
Request for app logs open

### ISSUE THREAD

**Issue by Woit** [wojciech-kulik/xcodebuild.nvim#129]
Hey!

We have command XcodebuildOpenLogs which is presenting build log file in bottom splitted non-editable window. Thats cool, but can you add another command for opening app_logs.log file? Im not using nvim-dap-ui, only dap with several keymaps, so i want to add open app_logs.log command to my run debug key. Also it will be cool, if buffer will updates automatically, when new log lines appears.

Or can you suggest how can i add this by myself? Thanks!

**Comment by wojciech-kulik** [comment]
Do you use tmux? If so you could just run in another pane:
```sh
tail -f .nvim/xcodebuild/app_logs.log
```

**Comment by Woit** [comment]
Im using iTerm2. Yep, right now i manually open pane and read the file, but im trying find a way to run it automatically on debugging start, and close when debug process is stop

**Comment by wojciech-kulik** [comment]
You could listen to dap events and open a window with `app_logs.log` file + run periodically `vim.cmd("checktime")` to refresh the buffer.

May I ask why don't you just use nvim-dap-ui? If you don't want all features you can just show console window and you will get exactly what you are looking for.
