### ISSUE TITLE
Error from nvim-dap "ENOENT: no such file or directory"

### ISSUE THREAD

**Issue by eranheres** [wojciech-kulik/xcodebuild.nvim#131]
Hi,
I am getting the following error while trying to run the debugger on iOS 17.3. It is happening both for the simulator and the device. Following this error, the build continues and runs, but it seems that it fails to connect to the debugger. I reverted to the [ios-dev-starter-nvim](https://github.com/wojciech-kulik/ios-dev-starter-nvim) and used the locked lazy-lock.json version, but it still happening. Please let me know if you need more information

...share/nvim-ios-starter/lazy/nvim-dap/lua/dap/session.lua:1193: ENOENT: no such file or directory
stack traceback:
^I[C]: in function 'error'
^I...share/nvim-ios-starter/lazy/nvim-dap/lua/dap/session.lua:1193: in function 'spawn_server_executable'
^I...share/nvim-ios-starter/lazy/nvim-dap/lua/dap/session.lua:1301: in function 'connect'
^I.../.local/share/nvim-ios-starter/lazy/nvim-dap/lua/dap.lua:1017: in function 'attach'
^I.../.local/share/nvim-ios-starter/lazy/nvim-dap/lua/dap.lua:376: in function 'run_adapter'
^I.../.local/share/nvim-ios-starter/lazy/nvim-dap/lua/dap.lua:408: in function 'maybe_enrich_config_and_run'
^I.../.local/share/nvim-ios-starter/lazy/nvim-dap/lua/dap.lua:504: in function <.../.local/share/nvim-ios-starter/lazy/nvim-dap/lua/dap.
lua:488>
^I[C]: in function 'xpcall'
^I...l/share/nvim-ios-starter/lazy/nvim-dap/lua/dap/async.lua:12: in function <...l/share/nvim-ios-starter/lazy/nvim-dap/lua/dap/async.l
ua:11>

**Comment by wojciech-kulik** [comment]
Hi! I'm not able to reproduce this issue on my side.

Please make sure that you updated all plugins to the latest version. Run also `:checkhealth xcodebuild` and verify results.

Have you modified something in the default configuration of nvim-ios-starter?

If nothing helps, I think it's more `nvim-dap` issue than this plugin`s issue. I don't see here anything related to the plugin itself.

**Comment by eranheres** [comment]
> Hi! I'm not able to reproduce this issue on my side.
> 
> Please make sure that you updated all plugins to the latest version. Run also `:checkhealth xcodebuild` and verify results. Also, make sure that all steps from: https://github.com/wojciech-kulik/xcodebuild.nvim#-debugger-configuration are done.
> 
> Have you modified something in the default configuration of nvim-ios-starter?
> 
> If nothing helps, I think it's more `nvim-dap` issue than this plugin`s issue. I don't see here anything related to the plugin itself.

Thanks, I do see some errors when running :checkhealth I will fix it and retest

**Comment by eranheres** [comment]
Yes, I had some setup issues with codelldb. thanks!
