### ISSUE TITLE
Crash when restarting an active debug session

### ISSUE THREAD

**Issue by tunaitis** [wojciech-kulik/xcodebuild.nvim#132]
Hey, thanks for creating this amazing plugin!

When I execute require("xcodebuild.integrations.dap").build_and_debug() while the debugger is still active, it replaces the active window with the following output:

```
; Symbol: mach_msg2_trap
; Source: unknown
184F4D86C: D0 05 80 92                mov    x16, #-0x2f
184F4D870: 01 10 00 D4                svc    #0x80
184F4D874: C0 03 5F D6                ret    
```

Below is the output from messages:

```
Launching application...
Application has been launched
...te/pack/lazy/opt/xcodebuild.nvim/lua/xcodebuild/util.lua:288: attempt to call local 'callback' (a table value)
stack traceback:
^I...te/pack/lazy/opt/xcodebuild.nvim/lua/xcodebuild/util.lua:288: in function 'call'
^I...y/opt/xcodebuild.nvim/lua/xcodebuild/platform/device.lua:33: in function 'call'
^I...zy/opt/xcodebuild.nvim/lua/xcodebuild/platform/macos.lua:46: in function 'launch_app'
^I...y/opt/xcodebuild.nvim/lua/xcodebuild/platform/device.lua:95: in function 'run_app'
^I.../opt/xcodebuild.nvim/lua/xcodebuild/integrations/dap.lua:130: in function 'call'
^I...y/opt/xcodebuild.nvim/lua/xcodebuild/project/builder.lua:96: in function <...y/opt/xcodebuild.nvim/lua/xcodebuild/project/builder.lua:72>
ECONNRESET
Build Succeeded [4 seconds]
```

For now, I circumvented the problem by creating a custom command to stop the active debugging session before starting a new one.

**Comment by wojciech-kulik** [comment]
Hi, it's expected behavior, because this command kills the current process and the debugger catches the signal. It's best to first kill the app and then run this command or just add additional action to your binding.

I use the default `<leader>dx` to stop the current session.

**Comment by tunaitis** [comment]
Great! Thanks for fixing this issue.

I actually prefer to keep the debugger running and make code changes on the fly. Then, I restart the debugger to see the result. Stopping and starting it later was an unnecessary step.
