### ISSUE TITLE
Incorrect Closure Expansion

### ISSUE THREAD

**Issue by BlackCatHehe** [wojciech-kulik/xcodebuild.nvim#137]
First of all, thank you for providing such an excellent plugin for nvim; I've really enjoyed using it. 
I encountered a particularly annoying issue during use: 
when I use closures, nvim does not provide the correct suggestions like xcode does, as shown below.

Have you encountered this problem during your use, and how can I solve it?

nvim:
![iShot_2024-04-20_14 20 09](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/39700053/9294b54c-8959-4165-a15c-5e1e0e8b26c2)

xcode:
![iShot_2024-04-20_14 21 10](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/39700053/cc1e2dac-b801-42f3-82d3-f0058d535313)

**Comment by wojciech-kulik** [comment]
Hi, completions are managed by sourcekit-lsp. I guess this feature is not available there and in Xcode it is provided by Xcode itself.

You could creata a feature request in their repo.

I also built some small function to transform this case, see https://github.com/wojciech-kulik/xcodebuild.nvim/discussions/33

**Comment by BlackCatHehe** [comment]
Great, I will try it. Thanks.
