### ISSUE TITLE
Could not connect codelldb 

### ISSUE THREAD

**Issue by BlackCatHehe** [wojciech-kulik/xcodebuild.nvim#139]
Hello, all functionalities work fine when I use xcodebuild. However, I encounter errors when I run in debug mode. 

I've correctly configured the codelldb path according to the sample project, and during the first debug, I was prompted to address codelldb's privacy concerns. However, subsequent runs present the problem as shown in the image below. 

The configurations for nvim-dap and nvim-dap-ui are directly copied from the sample project.

 I'm new to nvim, could you help me figure out what might be causing this issue?
 
<img width="703" alt="image" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/39700053/211341fb-3acf-444a-9803-95530c29f06e">
<img width="1053" alt="image" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/39700053/1624e2d7-92a0-463a-ba25-de9916b0bcce">
<img width="772" alt="image" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/39700053/f1d4617a-78c0-4faf-8fc2-69b8a994f13e">
<img width="436" alt="image" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/39700053/ae4227fa-3c10-4c76-93a3-58acb3c8e3f9">

**Comment by wojciech-kulik** [comment]
Hmm, that's weird, your configuration seems fine. Are you sure you downloaded codelldb for the correct architecture?

**Comment by BlackCatHehe** [comment]
My Mac is M3, and the version I downloaded is this one.
<img width="779" alt="image" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/39700053/7db5d2fa-1eae-4101-a773-ca8ed65fb95b">

When I directly run the command you provided under the codelldb file, the system prompts me to verify the privacy security of liblldb.dylib and libpython39.dylib first. After verification, it just gets stuck there without any response.
<img width="517" alt="image" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/39700053/78a9f1dc-e729-4155-8bcf-b1ace7874ee8">

**Comment by BlackCatHehe** [comment]
I tried again. I directly ran the following command in the terminal:

```bash
./codelldb --port 13000
```
Then, when using the xcodebuildDebug command, lldb can connect properly. However, when I stop the project from running, the codelldb running in the terminal also stops. At this point, I can't connect using xcodebuildDebug for two consecutive attempts.

I downloaded my Xcode from xcodesapp, and it comes with version numbers, like this:
<img width="916" alt="image" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/39700053/8ac5c3ff-4bb4-41f3-946d-b9317d055574">

**Comment by wojciech-kulik** [comment]
Ok, in this case I think you should report this issue in nvim-dap repository. If it works when you manually run codelldb. The process is managed by nvim-dap, the only thing xcodebuild does is to provide the configuration:
```lua
  return {
    type = "server",
    port = "13000",
    executable = {
      command = codelldbPath,
      args = {
        "--port",
        port or "13000",
        "--liblldb",
        lldbPath or "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/LLDB",
      },
    },
  }

```

**Comment by wojciech-kulik** [comment]
Oh, but wait, I just noticed that you've got a different path: `/Applications/Xcode-15.2.0.app`. So you need to provide the config manually.

Just add below `xcodebuild.setup`:

```lua
require("dap").adapters.codelldb = require("xcodebuild.integrations.dap").get_codelldb_adapter("PATH_TO_CODELLDB", "/Applications/Xcode-15.2.0.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/LLDB")
```

**Comment by BlackCatHehe** [comment]
It seems the issue is caused by the inability to start codelldb properly when I use xcodebuild debug-related commands.




> Oh, but wait, I just noticed that you've got a different path: `/Applications/Xcode-15.2.0.app`. So you need to provide the config manually.
> 
> Just add below `xcodebuild.setup(codelldbPath)` in `nvim-dap` config:
> 
> ```lua
> require("dap").adapters.codelldb = xcodebuild.get_codelldb_adapter(codelldbPath, "/Applications/Xcode-15.2.0.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/LLDB")
> ```

It worked! Thank you!

**Comment by jaekong** [comment]
For people finding this later:

I had the same error message, but it was from different cause.

```sh
export LC_CTYPE=en_US.UTF8 # or some other locale
```

I needed LC_CTYPE environment variable set up.

**Comment by wojciech-kulik** [comment]
@jaekong out of curiosity, how did you figure it out to define that env? :D
