### ISSUE TITLE
Working with two projects at the same time in different tmux sessions

### ISSUE THREAD

**Issue by FredericRuaudel** [wojciech-kulik/xcodebuild.nvim#140]
Hi! 

First, thanks for this great plugin and tutorials. I enjoy coding in swift again thanks to you 💙 

I'm using git worktree to setup several instances of my project in different branches to be able to work on multiple ticket at the same time.

The result is that I have several folder with different copy of my project like:

```
├── project-main
├── project-branch1
```

I have configured both project with a `buildServer.json` and I can build both project just fine using nvim that I run in different tmux sessions to be able to switch between them easily.

So my issue is that it seems that there is no way to make `ray-x/navigator.lua` plugin works on both instances at the same time. On the first project I configured, I can navigate my definition or find usages of my symbols but on the second one, it keeps saying "No Definition found" or just give no feedback.

After a lot of investigation and trying to understand how each of my plugins are working, I maybe get what can go wrong.

When I check my lsp processes, I get this:

```
❯ ps ax | grep lsp
33078   ??  Ss     0:07.31 /Applications/Xcode-15.2.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/sourcekit-lsp
70746   ??  Ss     0:01.43 /Applications/Xcode-15.2.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/sourcekit-lsp
```

I don't know how many should run at the same time, but I guess we get one per project running. So maybe my issue comes from the fact that when I open my second project, it launches a new lsp server but when it tries to communicate with it, it query the one from the other project and it returns nothing because the refs are not the same… 🤷‍♂️ 

What do you think? Could it be that? 🤔

**Comment by BlackCatHehe** [comment]
Same issue.

**Comment by wojciech-kulik** [comment]
LSP for iOS is tricky, recently I've got many problems with that. Hopefully, some new release of sourcekit-lsp will improve the stability.

I'm not familiar with LSP internals. You can ask this question:
https://github.com/apple/sourcekit-lsp/issues
or
https://github.com/SolaWing/xcode-build-server/issues

I guess they will be able to at least figure out what's wrong :).
