### ISSUE TITLE
Attempt to call field 'get_clients' (a nil value)

### ISSUE THREAD

**Issue by PBHDK** [wojciech-kulik/xcodebuild.nvim#141]
Hi!

I'm getting the following error when trying to change the scheme (amongst others).

I did some googling and apparently this might not be xcodebuild-related, but I was hoping that you might have some pointers anyway?

```
Updating project settings...
...lazy/xcodebuild.nvim/lua/xcodebuild/integrations/lsp.lua:47: attempt to call field 'get_clients' (a nil value)
stack traceback:
^I...lazy/xcodebuild.nvim/lua/xcodebuild/integrations/lsp.lua:47: in function 'restart_sourcekit_lsp'
^I....nvim/lua/xcodebuild/integrations/xcode-build-server.lua:32: in function <....nvim/lua/xcodebuild/integrations/
xcode-build-server.lua:31>
Project settings updated
```

**Comment by PBHDK** [comment]
Huh. `vim.lsp.get_clients` does indeed seem to be missign on my side. I'm using Neovim 0.9.5, i.e., the current Homebrew version. Seeing nothing suspicious in `:checkhealth` either.

**Comment by wojciech-kulik** [comment]
It turns out that actually, it's available in the new version of Neovim (nightly build). I thought it's also available in 0.9.5. Weird that nobody reported it :D I will have to migrate it to something that is available in 0.9.5

**Comment by wojciech-kulik** [comment]
It's a pitty that the documentation doesn't mention in which version the specific function is available:
https://neovim.io/doc/user/lsp.html#vim.lsp.get_clients()

**Comment by PBHDK** [comment]
I was going to say that it works with Homebrew's HEAD version of Neovim! 😄 

Apparently, `vim.lsp.get_clients()` is supposed to replace `vim.lsp.get_active_clients()`and `vim.lsp.buf_get_clients()`anyway:
https://neovim.io/doc/user/deprecated.html

I'll stick with the nightly for now. Maybe you can avoid a change if 0.1.0 becomes the stable version soon - don't know what Neovim's release plan's are ...

**Comment by PBHDK** [comment]
Ah, Neovim version 0.10 is due on May 7: https://github.com/neovim/neovim/milestone/36

**Comment by wojciech-kulik** [comment]
I think I should support at least 0.9.5, so I will provide the fix  :). It shouldn't be a big problem :).

**Comment by PBHDK** [comment]
Brilliant! Thanks for your help on this!
