### ISSUE TITLE
`pymobiledevice3` not installed

### ISSUE THREAD

**Issue by PBHDK** [wojciech-kulik/xcodebuild.nvim#142]
Hi!

xcodebuild is not finding my `pymobiledevice3` installation, even though it is clearly installed. 

`:checkhealth` gives: 
```
- WARNING pymobiledevice3: not installed. Required for debugging on physical devices and/or running apps on
      devices below iOS 17. (https://github.com/doronz88/pymobiledevice3)
```

Is it possible that it is using the wrong Python version? How would I be able to check?

**Comment by wojciech-kulik** [comment]
Hi,

it just checks if `pymobiledevice3` is detectable. What happens if your run `pymobiledevice3` from terminal?

Search paths should be the same by default in Neovim and in the terminal.

**Comment by PBHDK** [comment]
Oh, sorry, never mind, it wasn't in my `PATH`. Was an easy fix on my side. Thanks for your help!
