### ISSUE TITLE
Some problem when build.

### ISSUE THREAD

**Issue by 0xnofoot** [wojciech-kulik/xcodebuild.nvim#15]
When I start build, there is a error.

Vim:E482: Can't open file /Volumes/KST/qwe/qwe/.nvim/xcodebuild/report.json for writing: no such file or directory
stack traceback:
^I[C]: in function 'writefile'
^I...are/nvim/lazy/xcodebuild.nvim/lua/xcodebuild/appdata.lua:41: in function 'write_report'
^I...nvim/lazy/xcodebuild.nvim/lua/xcodebuild/coordinator.lua:220: in function <...nvim/lazy/xcodebuild.nvim/lua/xcodebuild/coordinator.lua
:213>

can't find the ...../qwe/qwe/.nvim , this directory.

but my project name is qwe, xcodebuild.nvim should find ....../qwe/.nvim, this should be the right path, and settings.json is right here.

so the wrong path occurred in messages.

I try mkdir ....../qwe/qwe/.nvim, then build succeed.

I really want to know how to solve it, Is this my own configuration problem or is it a bug?

<img width="1680" alt="截屏2023-12-18 19 17 47" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/108229781/b5fd82f5-341b-4b5a-8513-32154d19a49a">
<img width="1680" alt="截屏2023-12-18 19 18 36" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/108229781/cb060ab5-955a-44b8-8646-76d3eb2792cb">

**Comment by wojciech-kulik** [comment]
Did you open Neovim from `/KST/qwe`? It looks like it was opened from `/KST/qwe/qwe` instead

**Comment by 0xnofoot** [comment]
Sorry I didn't notice that nvim should be opened in the root directory, but everything was fine when I did.
I also have one more question: even if I fixed the working directory of nvim in the project root directory, opening nvim in the subdirectory still won't build correctly, but it can setup correctly. Is that normal? Is there any way to open nvim in a subdirectory and still use the plug-in?

and last , thank you for your plugin and artical, this is very helpful for me, thank you very much!

**Comment by wojciech-kulik** [comment]
Unfortunately, the assumption is that you have to start the project from your root directory, so currently it's not supported to perform xcodebuild actions if you open Neovim from a subfolder. 

However, if you set up the project from a subfolder, it should build the project correctly. I've just checked it and it works with my project. 

But please note that files like xcodeproj/xcworkspace are only searched in the current folder and subfolders, so if it's in a parent directory, you won't be able to configure the plugin using wizard.

Also, ensure that your file explorer is not changing cwd when navigating between files (sometimes people use this feature).

**Comment by 0xnofoot** [comment]
thank you for your answer, It's not a big deal. I love this project.
