### ISSUE TITLE
Stuck at loading devices

### ISSUE THREAD

**Issue by jaimejazarenoiii** [wojciech-kulik/xcodebuild.nvim#154]
Not sure why is it like this.

My project dir goes like this

-> .git
-> Folder
  -> Project.xcodeproj

<img width="1124" alt="Screenshot 2024-06-25 at 11 42 17 AM" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/32864278/6865b166-e022-4f91-9dbc-441a93324db3">

**Comment by jaimejazarenoiii** [comment]
NVM, it was an issue with my packages.

**Comment by badloop** [comment]
Do you mind sharing what the fix was?  I'm stuck at this as well.

**Comment by wojciech-kulik** [comment]
@badloop have you built the app in Xcode first?
