### ISSUE TITLE
UIKit components are not available in code suggestions/completions

### ISSUE THREAD

**Issue by bengidev** [wojciech-kulik/xcodebuild.nvim#16]
Hello, i want to say thank you very much for your great work and article 🍻 .

First, i want to ask you about UIKit components which are not available in code suggestions or code completions. Maybe this problem comes from [sourcekit-lsp](https://github.com/apple/sourcekit-lsp), or maybe something wrong in my `nvim-lspconfig`. 

The second thing is when i open the `Swift` file without `buildServer.json`, it will work normally. And if i open the directory which contains the `buildServer.json`, then the code completions/suggestions are gone or some of them are missing.

This is my full config, i've adjust the config to match [LazyVim](https://www.lazyvim.org) config style.
[My NVim Config](https://github.com/bengidev/Bengi_LazyVim_Configuration)

This is my `nvim-lspconfig`
```lua
return {
  "neovim/nvim-lspconfig",
  event = { "BufReadPre", "BufNewFile" },
  dependencies = {
    "hrsh7th/cmp-nvim-lsp",
    { "antosha417/nvim-lsp-file-operations", config = true },
  },
  opts = {
    servers = {
      sourcekit = {
        cmd = {
          "/Applications/Xcode-15.2.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/sourcekit-lsp",
        },
        root_dir = function(filename, _)
          local util = require("lspconfig.util")

          return util.root_pattern("buildServer.json")(filename)
            or util.root_pattern("*.xcodeproj", "*.xcworkspace")(filename)
            or util.find_git_ancestor(filename)
            or util.root_pattern("Package.swift")(filename)
            or util.root_pattern("*.swift")(filename)
        end,
        capabilities = {
          require("cmp_nvim_lsp").default_capabilities(),
        },
      },
    },
  },
}
```

This is my `buildServer.json`
```json
{
	"name": "xcode build server",
	"version": "0.2",
	"bspVersion": "2.0",
	"languages": [
		"c",
		"cpp",
		"objective-c",
		"objective-cpp",
		"swift"
	],
	"argv": [
		"/usr/local/bin/xcode-build-server"
	],
	"workspace": "/Users/beng/Downloads/TestProjectNew/TestProjectNew.xcworkspace",
	"build_root": "/Users/beng/Library/Developer/Xcode/DerivedData/TestProjectNew-fchuuouqovwzrbbyrhugratmxctd",
	"scheme": "TestProjectNew",
	"kind": "xcode"
}
```

This is my screen-shoots
![Screenshot 2024-01-22 at 05 56 41](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/c1b8e748-c4c0-48d8-bc31-e5bea7b9afea)
![Screenshot 2024-01-22 at 05 58 34](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/da8ccba7-d955-4ca4-bbef-dc973aed15f7)
![Screenshot 2024-01-22 at 05 59 16](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/fcae3720-7217-4ea2-8202-9be87811e6a4)
![Screenshot 2024-01-22 at 08 27 17](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/3f16b425-7dff-465a-8261-81c1655f674e)
![Screenshot 2024-01-22 at 08 27 37](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/73544a02-0313-4fd9-905d-970a8e98f436)

**Comment by wojciech-kulik** [comment]
Hi,
thank you for the feedback!

The result of `LspInfo` looks good. A few ideas to try:
1. Open the project in Xcode, clean & build, run `xcode-build-server` again, reopen Neovim
2. Did you open Neovim in your project root directory? Just run `nvim`, not `nvim .`
3. Try using this lsp configuration, just change Xcode path: https://github.com/wojciech-kulik/ios-dev-starter-nvim/blob/main/lua/starter/plugins/nvim-lspconfig.lua
4. Check what is in lsp logs `:LspLog`

Btw. what color scheme do you use?

**Comment by bengidev** [comment]
Hello. Thank you for your suggestions, i'll try all of that later.

This is my [iTerm2](https://iterm2.com) themes:
- [Catppuccin](https://github.com/catppuccin/iterm) for colors
- [Colorls](https://github.com/athityakumar/colorls) for terminal icons
- [Cascadia Cove Nerd Font](https://www.nerdfonts.com)

And set the blur with transparency inside iTerm2 Settings -> Profiles -> Window section. 
Hope it helps 🍻 .

**Comment by wojciech-kulik** [comment]
Thank you! Actually, I'm using all the same (only with a different font), but it looks like you've got different colors for Catppuccin. 

For example, `class`/`override` should be purple, but your colors are different. I'm using this: https://github.com/catppuccin/nvim

**Comment by bengidev** [comment]
Yeah, i'm using that too. But i choose the `mocha` variant, and applying inside [iTerm2](https://iterm2.com/) and [NeoVim](https://neovim.io).

Maybe you forgot to select the [Catppuccin](https://github.com/catppuccin/iterm) variant.
