### ISSUE TITLE
xcode-build-server's --skip-validate-bin flag support

### ISSUE THREAD

**Issue by ychie** [wojciech-kulik/xcodebuild.nvim#162]
Hey @wojciech-kulik,

My project requires passing --skip-validate-bin to the xcode-build-servers config command for autocompletion to work. However, I encountered an issue where this flag was removed whenever I changed the scheme using your plugin. To fix this, I added the ability to enable/disable this flag and save the state inside .nvim/settings.json.
https://github.com/ychie/xcodebuild.nvim/commit/c693370e013622753d8cc2eae177db5c9e727924

![Screenshot 2024-08-11 at 20 46 50](https://github.com/user-attachments/assets/b446649b-29f8-4848-b9b7-10461bec5e88)

Would you be interested in including this functionality in your plugin? If so, should I create a pull request?

**Comment by wojciech-kulik** [comment]
Hi! 

I don't have much time right now, but sure, you can create a pull request.

You can extend the config for xcode-build-server to include extra arguments.

For the reference, you can check out this commit to see how to add a new option:
https://github.com/wojciech-kulik/xcodebuild.nvim/commit/3fd5b2eef5a5e12e64e1fccc1de4b7e5d351967c

Please also read: https://github.com/wojciech-kulik/xcodebuild.nvim/blob/main/CONTRIBUTING.md

**Comment by wojciech-kulik** [comment]
Closing the issue because of lack of activity.
