### ISSUE TITLE
Project setup without connected device

### ISSUE THREAD

**Issue by belyakov-am** [wojciech-kulik/xcodebuild.nvim#168]
Hey!
I'm trying to setup this plugin without a connected device (I see an empty list on `Select Device` stage of project setup)
I can't find a way to skip this stage, so I'm wondering if it's even possible

**Comment by wojciech-kulik** [comment]
Hi,
The list shouldn’t be empty. Please run`:checkhealth xcodebuild` to see if everything is configured properly.

**Comment by belyakov-am** [comment]
Thanks for a quick response!
Turns out `xcodebuild` wasn't configured properly
[This issue](https://github.com/nodejs/node-gyp/issues/569) helped
