### ISSUE TITLE
Build & Test reported as success, tests run, but the actual project is not even building

### ISSUE THREAD

**Issue by tadelv** [wojciech-kulik/xcodebuild.nvim#169]
Hi,

Been using xcodebuild-nvim for a few months now, quite successfully. But recently I'm getting a lot of false positives when running tests and my code does not actually compile. Seems like xcodebuild finds an old version that could be built and runs tests against that. If I open the project in Xcode, there is a bunch of errors both in tests as well as the source, which are not shown in nvim.
Here's my nvim config, if that helps: https://github.com/tadelv/dotfiles/tree/master/config/nvim/lua/vid/plugins

it might be also a misconfig of something else perhaps, like lsp or xcode-build-server maybe ...

Any help is appreciated!

**Comment by tadelv** [comment]
as a bonus, I'm also curious to figure out, how to show why a particular test is failing. Trouble doesn't give me any more specific info other than `Test failed`

**Comment by wojciech-kulik** [comment]
Hi! Sorry for the late reply I've been pretty busy recently. Could you share your logs from the build that is false-positive? 

If it contains sensitive information you can try obfuscating it. You can find logs in your `project_dir/.nvim/xcodebuild/original_logs.log`. Also files `report.json` and `tests.json` would be useful if you are able to provide them.

> as a bonus, I'm also curious to figure out, how to show why a particular test is failing. Trouble doesn't give me any more specific info other than Test failed

This plugin adds issues to quickfix list, so you need to run trouble using the right mode `:Trouble quickfix`. You can also see it using telescope.

**Comment by tadelv** [comment]
Hey,
No worries, better late than never :)
As I run this setup on a work project, time was of the essence and I
resorted to Xcode to find and fix the issue. The compilation of source
files (not for tests) failed somewhere and xcodebuild.nvim wasn't picking
it up. I do not have the logs anymore, but if the issue happens again, I
will obfuscate the logs and post them here for sure. But not at least for
two weeks as I will be travelling. 😅

Thanks for the hint regarding trouble and telescope, will check them out!

I do have one more question, if you have the time and energy to answer
perhaps:
Does the plugin automatically feed sourcekit-lsp after initial
xcode-build-server setup and first successful build (and successive builds
after that)? I notice when I add new files to the project (We use xcodeproj
that references local spm packages - file added inside package, not to the
project), I don't get autocomplete there. But it could also be an lsp issue
I guess - it is very flakey for me.

**Comment by wojciech-kulik** [comment]
Regarding your last question, as far as I remember (I was working on a similar project) you have to rebuild after adding a file in a different package. An incremental build from Neovim should be enough. If you add a file to the same package, I think xcode-build-server handles currently that case, and autocompletion should work automatically.

Regarding this ticket, I'm closing this issue, but feel free to reopen it once it happens again :)

**Comment by tadelv** [comment]
Awesome, thank you so much!
