### ISSUE TITLE
The LSP does not look at my include path

### ISSUE THREAD

**Issue by bruhderek** [wojciech-kulik/xcodebuild.nvim#170]
Hi guys! I'm really liking this plugin so far, but I'm confused about the LSP.

This code compiles; however, the LSP does not respect the include path of the xcode project:
<img width="1100" alt="image" src="https://github.com/user-attachments/assets/95f91824-5a05-4a08-89d4-cf23acbeb88b">

**Comment by wojciech-kulik** [comment]
Hi! LSP is not a part of this plugin. I'm not sure if it is possible to configure Neovim to work with Objective-C. 

It works with Swift but it requires "xcode-build-server" tool to let LSP understand the project structure. Maybe in SolaWing will be able to help you: 
https://github.com/SolaWing/xcode-build-server

**Comment by bruhderek** [comment]
@wojciech-kulik thanks for info. I found out i had clangd installed for some reason xD
