### ISSUE TITLE
Sourcekit error: Loading the Standard Library Failed

### ISSUE THREAD

**Issue by paulhdk** [wojciech-kulik/xcodebuild.nvim#180]
After upgrading to macOS Sequoia yesterday, I'm now seeing the following error when trying to access the definition of a variable.

> Error when executing textDocument/definition : sourcekitd request failed: error respons e (Request Failed): Loading the standard library failed

Might be worth noting that I switched from xcode-beta to xcode after upgrading macOS.

xcodebuild config:
```lua
		require("xcodebuild").setup({
			code_coverage = {
				enabled = true,
			},
			commands = {
				extra_build_args = "-parallelizeTargets -toolchain swift-latest",
				extra_test_args = "-parallelizeTargets -toolchain swift-latest",
			},
		})
```

lsp config:
```lua
			lspconfig.sourcekit.setup({
				filetypes = { "swift" },
				cmd = { "sourcekit-lsp" },
				capabilities = require("cmp_nvim_lsp").default_capabilities(),
				root_dir = function(filename, _)
					local util = require("lspconfig.util")
					return util.root_pattern("buildServer.json")(filename)
						or util.root_pattern("*.xcodeproj", "*.xcworkspace")(filename)
						or util.find_git_ancestor(filename)
						or util.root_pattern("Package.swift")(filename)
				end,
			})

```

Not sure if this is related: https://forums.swift.org/t/sourcekit-lsp-loading-the-standard-library-failed/73818

Of course I tried running xcode-build-server again as well as clean building from xcode. My project appears to build in Neovim as well.

Any thoughts?

**Comment by wojciech-kulik** [comment]
Hmm, I'm using Sequoia with the latest Xcode and it works fine. Maybe try removing ` -toolchain swift-latest`?

**Comment by wojciech-kulik** [comment]
Also, use:

```
cmd = vim.trim(vim.fn.system("xcrun -f sourcekit-lsp")),
```

instead of
```
cmd = { "sourcekit-lsp" },
```

**Comment by paulhdk** [comment]
Hm. It's working now, but I'm not quite sure what ended up fixing it. In any case, thanks for taking a look! Closing as completed!
