### ISSUE TITLE
Can't use `xcbeautify` if not on PATH

### ISSUE THREAD

**Issue by John-Colvin** [wojciech-kulik/xcodebuild.nvim#182]
e.g.

```
require("xcodebuild").setup({
    logs = {
        logs_formatter = config_dir .. "/../../tools/xcbeautify --disable-colored-output --disable-logging"
    }
})
```

this triggers the `if config.logs_formatter:find("xcbeautify") and vim.fn.executable("xcbeautify") == 0 then` line in `xcode_logs/panel.lua`, which means the `logs_formatter` is not used. If I comment out that `if` block then it is called correctly and I see beautified logs.

**Comment by wojciech-kulik** [comment]
Could you switch to `fix/issue-182` and see if it resolves your issue?
