### ISSUE TITLE
set filetype of swiftformat files to swift so documentation is rendered as expected

### ISSUE THREAD

**Issue by iMostfa** [wojciech-kulik/xcodebuild.nvim#189]
Hi, 

i really like your work, i feel good to open Xcode way less than usual. 

sharing this in case it's helpful for anyone.

when i open the docs of any type in standard library (like String, Date..etc) 

the typesetter doesn't detect the filetype, so it appeared as a plain text, after doing this, it works well: 

```lua
vim.api.nvim_create_autocmd({ "BufRead", "BufNewFile" }, {
  pattern = "*.swiftInterface",
  command = "set filetype=swift",
})
```

Before: 

<img width="500" alt="image" src="https://github.com/user-attachments/assets/954185e0-b22c-4e52-a323-3b605527e9f8">

After: 
<img width="523" alt="image" src="https://github.com/user-attachments/assets/ec92b915-4b61-4ec4-9039-d7074ce45e93">

**Comment by wojciech-kulik** [comment]
Correct, probably it would be best to add it to the plugin so that people don't have to figure it out on their own!

Good idea!

**Comment by wojciech-kulik** [comment]
Interesting thing, I discovered that since Neovim v0.11.0 (nightly) it happens automatically. I'm not sure why. 

Maybe it takes somehow that information from LSP.

**Comment by Almaz5200** [comment]
> I discovered that since Neovim v0.11.0 (nightly) it happens automatically. I'm not sure why.

I think it's due to [that](https://github.com/neovim/neovim/blob/2c88cfcac42d0a4e0b1a1396539b5add807c336c/runtime/lua/vim/filetype.lua#L1149) and [that](https://github.com/neovim/neovim/pull/30350), basically a huge extension to filetype mapper :D

**Comment by wojciech-kulik** [comment]
@Almaz5200 nice catch! Thank you for the links!
