### ISSUE TITLE
Show or detect code completions/suggestions from external plugins/frameworks

### ISSUE THREAD

**Issue by bengidev** [wojciech-kulik/xcodebuild.nvim#19]
Hello, have problems when using external frameworks/plugins inside [Neovim](https://neovim.io).

Let say i want to use [RxSwift](https://github.com/ReactiveX/RxSwift) functionalities in my iOS app project. Then i install the frameworks with SPM like usual, and the frameworks was successfully installed and ready to use.

if i use the frameworks inside XCode, it will show the code suggestions/completions perfectly, like the screenshoots below.
![Screenshot 2024-01-27 at 09 43 26](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/5145b48e-997d-49d8-a4f6-ca81f7e7ec5e)

And this screenshoots below shows that nvim cannot export and show/detect the installed frameworks inside XCode.
![Screenshot 2024-01-27 at 09 45 28](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/6950e452-a838-4c2f-9897-18dcf48c0071)

This screenshoots below shows that external frameworks installed correctly.
![Screenshot 2024-01-27 at 09 44 07](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/c3656f46-568a-439b-895c-923e837b51c0)

And this is my questions:
- Are you have the same problems when working with nvim, or there's something missing from my nvim configuration?
- Is that possible to work with the external frameworks inside nvim?
- Or nvim with lsp just can help with code completions/suggestions from server, and cannot provide the same behavior when working with external frameworks?

I hope you're not confusing with my explanations. Thanks 🍻

**Comment by wojciech-kulik** [comment]
Hello,
it's a matter of LSP, it looks like in your case it doesn't understand the project. Try opening the project in Xcode, clean build, run `xcode-build-server` command again, open Neovim in root directory where `buildServer.json` is (call just `nvim` from there) and see again if it works.

**Comment by bengidev** [comment]
Hello again, mate.

So i've just try to delete my own NeoVim configuration and replace it with yours, and these are the results:

- Try to correct neovim config with your config.
![Screenshot 2024-01-28 at 06 39 27](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/0a621acd-d909-4b37-92e9-92b0e772faa8)

- NeoVim starts and installing plugins based on your NeoVim configurations:
![Screenshot 2024-01-28 at 06 27 15](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/1e4409fa-3498-4e80-a638-23a40607e191)

- I've changed the LSP path, LLDB path, and the others to match with my computers path:
![Screenshot 2024-01-28 at 06 13 07](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/131e00f2-bbcf-4e27-983c-9f4b67a281b1)

- This is my generated buildServer.json from xcode-build-server:
![Screenshot 2024-01-28 at 06 11 37](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/f2ce63a9-f95b-4b71-a202-16dde190eadc)

- I try to open my XCode directories which i was generated the buildServer.json file in the root of the directories
![Screenshot 2024-01-28 at 06 55 35](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/062afefd-5999-47f6-84d0-f7e538706fb8)

- I try to import some library from Apple inside my Swift file in the XCode directories, and i think LSP failed to run, without knowing what the import is.
![Screenshot 2024-01-28 at 06 35 02](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/ffdb3b77-2e7f-4046-acb2-6a63e8796e98)

- I try to open LspInfo for check the LspStatus, but it says successfully start.
![Screenshot 2024-01-28 at 06 35 28](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/2d830c6b-339d-4612-a85b-95f49ed763f8)

- I try to open LspLog to try find out whats happening, and these errors was thrown:
![Screenshot 2024-01-28 at 06 09 07](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/3aac7e1f-ddb1-4d95-9cfd-866c1f5f60d1)
![Screenshot 2024-01-28 at 06 37 00](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/67a22426-f7c4-4834-bae8-fca57407b452)

And, with your config, the LSP for other languages was died/failed to start, i don't know what the reasons.
So, that was my report for you.

Have a good day, mate 🍻

**Comment by wojciech-kulik** [comment]
I see that your "buildRoot" is incorrect in `buildServer.json` it should point to project in `DerivedData` folder.
Try clean build from Xcode and run then `xcode-build-server` again. If `buildRoot` is still incorrect, try setting it manually.

You can also report issue to: https://github.com/SolaWing/xcode-build-server
This repository would be more relevant to resolve issues with LSP. As this plugin doesn't affect any LSP behavior.

**Comment by bengidev** [comment]
Hello, i've try to create and generate simple project from XCode to try your suggestions. And i think the old issue still persist.

- This is my simple generated project structure from XCode:
![Screenshot 2024-01-29 at 11 04 08](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/432c1c61-50fe-4e88-a040-0f771827f7ad)

- This is my generated `buildServer.json`:
![Screenshot 2024-01-29 at 11 03 53](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/188c9a64-7cc1-412e-89b8-749984644aef)

- And this is the results when i'm trying to `import Foundation`:
![Screenshot 2024-01-29 at 11 03 35](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/3253ebd1-2684-4f2c-945e-222426a8c270)

I will try to report into this repo too: [https://github.com/SolaWing/xcode-build-server](https://github.com/SolaWing/xcode-build-server)
Thank you very much for your attention.
