### ISSUE TITLE
Is it possible to add support for `target_for_file_atPath` ?

### ISSUE THREAD

**Issue by iMostfa** [wojciech-kulik/xcodebuild.nvim#199]
Hello, 

I've been using nvim for with Xcodebuild.nvim and i'm really enjoying it, Thanks to your great work, 

nonetheless, i have some small problems, mostly related to the fact that i'm working on a quite complex project structure. 

so i wanted to ask if it's possible (technically at least) to be able to provide the target from the config for a new file that was just created ? 

something similar to `should_update_project` but it returns the `String` of the target. 

more context: 

my project Structure Can be -simplified- to be like this: 

```
AppName.xcworkspace
- MonolithModule.xcodeproj // (links all child modules, when run, it opens the app in simulator)
- Pods.xcodeproj (Contains all child modules, something like, LoginScreen, CancelScreen` 
```

by default i have XcodeBuildServer pointing to MonolithModule because this's how i can build and run the app.

when i add a file to one of the modules inside Pods, targets inside Pods isn't detected, (Which is expected behaviour given that i'm poitning to `MonolithModule`)

currently i need to switch my xcodeBuildServer config to point to the modules, to be able to add files, which works, but kinda exhausting because i always need to run the app. 

currently i defer adding new files to the end of my workflow, so i keep adding my logic into existing files, then at the end i move all of them to new files after pointing to the new module. 

another alternative to this issue would be having the option of providing a custom run scheme/project. 

so i will get my XcodeBuildServer pointing to `Pods` but when i run the app, it will run the main project and main target

Thanks a lot for you, i want to know if it's possible, because if you think that it's worth it, i might try to support it and open a PR.

**Comment by wojciech-kulik** [comment]
Hmm, it looks like #188 might be what you are looking for :). 

If you set:
```
 integrations = {
    nvim_tree = {
      find_xcodeproj = true, -- instead of using configured xcodeproj search for xcodeproj closest to targeted file
    },
},
```

The closest `xcodeproj` will be used instead of the one configured for the project. Let me know if it resolves your issue.

**Comment by iMostfa** [comment]
@wojciech-kulik i remember that i tried this option, but it didn't work for me, i will try it again today and inform you.

**Comment by iMostfa** [comment]
@wojciech-kulik didn't help me, still showing the targets from the main project :/

**Comment by wojciech-kulik** [comment]
How do you add a file?

**Comment by Almaz5200** [comment]
I think #188 doesn't work because it doesn't try all of the .xcodeproj files in a directory, just the first one it finds, probably alphabetically. So if MonolithModule and Pods are in the same folder it likely tries MonolithModule, fails, and moves on.

Or maybe it even quits right away as soon as it gets to cwd

**Comment by wojciech-kulik** [comment]
Yeah, it depends on the structure of the project. I assumed that each `xcodeproj` has its own folder, that way the search should work.

**Comment by wojciech-kulik** [comment]
Now when the project manager is refactored, I think we could add a function that would allow to return a project path based on filepath instead of automatic search

**Comment by iMostfa** [comment]
Thanks, i will get back to you if i managed to narrow down my problem/featureRequest to simple manner, ideally i want something like `target_for_file_atPath` but i don't know if Xcodebuild will accept it (specifying target, for a specific XcodeProject)

**Comment by wojciech-kulik** [comment]
@iMostfa I added a function `config.project_manager.project_for_path` in #218. Could you switch there and see if it resolves your issues?

Basically, you just need to return a project path based on the file path. The target will be recognized automatically based on the file location. You can return `nil` to  use the configured project.

However, it won't work with the target picker.

**Comment by wojciech-kulik** [comment]
@iMostfa let me know if you will be able to test it

**Comment by iMostfa** [comment]
Hi, I will test within 24 hours, many thanks for you

**Comment by iMostfa** [comment]
Hi, i tested it, 
it worked for some projects, but not all of them, i don't really know why. 

can you inform me if there's a verbose logging mode so i help you check why it didn't work for some projects ?? 

i noticed the following: 

it worked for: 
- statically generated `xcodeproj`s
- the `project.pbxproj` lineCount is small, like 1253 line.

it didn't work for: 
- dynamically generated `xcodeproj` (it's the Pods.xcodeproj`) which is generated on `pod install`
- `project.pbxproj` **wasn't modified/changed** after the file was added/created (despite not showing any errors!)
- thus, Xcode didn't see it, and xcodebuild didn't build it, until i regenerated the project. [which aligns with the problem]
- finally, `project.pbxproj` lineCount is so big, maybe this's causing some problems ? 270,937 line

**Comment by iMostfa** [comment]
@wojciech-kulik 
i will try to make a minimal sample project, but it will take me sometime.

but i tried to do something else to verify the problem, i did choose my `Pods.xcodeproj` project from `Configuration wizard`
and then tried to add a file, it also didn't work. 

so it looks like there's a problem for that specific Pods.xcodeproj

and this problem isn't related to the new feature that you added `project_for_path` for me.

Which is also helpful, because it works well for all projects when we exclude the broken one.

this's how i configured it, i simply hard coded it to be able to test faster
```lua
project_manager = {
        project_for_path = function(path)
          print(path)
          return "Pods/Pods.xcodeproj"
        end,
      }
```

**Comment by wojciech-kulik** [comment]
It has to be an absolute path (not relative). Try with that.

**Comment by wojciech-kulik** [comment]
Let me know once you try it with the full path in your `project_for_path`.

**Comment by iMostfa** [comment]
same problem, it works for all nested projects as expected, but doesn't work for the generated Pods.xcodeproj

```lua
function(path)
          print(path)
          return "/Users/mostafa.essam/projectName/Pods/Pods.xcodeproj"
end
```


i still think that the PR you created is useful and needed. because of the following part from my previous comment:

> i tried to do something else to verify the problem, i did choose my Pods.xcodeproj project from Configuration wizard
and then tried to add a file, it also didn't work.
> so it looks like there's a problem for that specific Pods.xcodeproj

i will try to create a simple project showing the problem and get back to you

**Comment by wojciech-kulik** [comment]
Ok, so in general it works as expected? The only problem is with `Pods.xcodeproj`?

I would close this ticket then and please create a bug for `Pods.xcodeproj` integration.

**Comment by iMostfa** [comment]
Correct, thanks for your work this ticket can be closed, and i will open a new ticket. 

Thanks for you.
