### ISSUE TITLE
Could not launch app (code: 4)

### ISSUE THREAD

**Issue by sainttttt** [wojciech-kulik/xcodebuild.nvim#2]
Hi! I'm having a few problems running xcodebuild.nvim in general. First of all, Xcodebuildsetup shows a blank telescope selector. I manually created the settings.json file and was able to build the project, however the app won't launch in the simulator. I can confirm that the destination field in my settings.json is for the  correct simulator - I only have one installed and removed all inactive ones.
Any help would be appreciated - thanks and God bless!

**Comment by wojciech-kulik** [comment]
Hi!

Please provide these information:
1. What is your setup (mac, macOS, Xcode version, etc.)?
2. What is your project (iOS/macOS app, what iOS you target)?
3. What simulator do you use?
4. How is your Xcode installed? From the App Store or manually?
5. Anything unusual in your setup?
6. Could you share your settings.json?
7. What is structure of your project? Do you use xcodegen/tuist, do you have xcworkspace or only xcodeproj, do you use some package manager like CocoaPods?
8. Is the plugin able to perform any other operations? Build, test, install, etc.?
9. Have you tried to perform the same operation manually? `xcrun simctl launch --terminate-running-process '<DESTINATION>' '<BUNDLE_ID>'. What's the result?

Error code 4 means most likely that the app doesn't exist on your simulator. So probably some previous command failed as well like build or install.

**Comment by wojciech-kulik** [comment]
I didn't get an answer. If you are still experiencing this issue, please download the latest version and try it again. 

If it still occurs, please provide the requested details and reopen this issue.
