### ISSUE TITLE
nvim freezes while building

### ISSUE THREAD

**Issue by colinmarc** [wojciech-kulik/xcodebuild.nvim#208]
Hi, thanks for the great plugin!

I'm using tuist, and I've noticed that when I run `tuist build`, nvim freezes up for 5-10 seconds. It happens whenever tuist gets to the stage `Copying build products to...`.

I'm happy to debug more, but I'm not sure where to start. Thanks in advance for any pointers!

**Comment by wojciech-kulik** [comment]
How do you call it? Just `:!tuist build`? Commands launched this way are blocking, you can't do anything while it's running.

**Comment by colinmarc** [comment]
Thanks for the quick response!

No, I'm running it from a terminal. So it must be something triggered by detecting the file changes. Note that the build dir is under `.gitignore`.

**Comment by wojciech-kulik** [comment]
Observer processes and see what's taking resources, maybe it will lead to some conclusions. If not, the probably it would be better to ask in Tuist repository, I haven't been using it for a long time, so I'm not up-to-date.

**Comment by colinmarc** [comment]
I'll continue to try and debug, thanks. I think it's this plugin or the swift lsp causing problems, though - I'm not maxed out on CPU or anything and the rest of my computer is perfectly responsive, it's just nvim that freezes.

**Comment by wojciech-kulik** [comment]
I don't think it could be the plugin, because it doesn't track anything and doesn't perform any operations in the background. Bigger chance that it's something LSP related.

**Comment by wojciech-kulik** [comment]
You could try disabling LSP for all buffers and try then.

**Comment by iMostfa** [comment]
not sure if it's related, 
but if you use SourceKit of Xcode 16, then it's broken. 
https://github.com/swiftlang/sourcekit-lsp/issues/1541

i reported this to Apple, and they fixed it, my solution was to replace the SourceKit inside Xcode 16 with the one of Xcode 15

**Comment by colinmarc** [comment]
I was able to fix it by placing the build directory in `/tmp`. Still not sure on the cause. 🤷 Thanks for the help!
