### ISSUE TITLE
v1.3.0 fails to load

### ISSUE THREAD

**Issue by humblehacker** [wojciech-kulik/xcodebuild.nvim#21]
I updated to the latest version today, and the plugin no longer loads for me. I don't get any errors on start, but none of the commands are present and none of my custom keymaps for this plugin are working.

I narrowed it down to this commit: a32762993177117b5fce4aa53490d7df4f912da4. I'm not quite sure how to debug this.  

I'm loading the plugin with lazy.nvim, and this is my config:

```lua
return {
  "wojciech-kulik/xcodebuild.nvim",
  dependencies = { "nvim-telescope/telescope.nvim" },
  config = function()
    require("xcodebuild").setup({
      logs = {
        auto_open_on_failed_tests = true,
        auto_open_on_failed_build = true,
        auto_focus = false,
        auto_close_on_app_launch = true,
      },
      commands = {
        extra_build_args = "-skipMacroValidation"
      },
    })

    vim.keymap.set("n", "<leader>xl", "<cmd>XcodebuildToggleLogs<cr>", { desc = "Toggle Xcodebuild Logs" })
    vim.keymap.set("n", "<leader>xb", "<cmd>XcodebuildBuild<cr>", { desc = "Build Project" })
    vim.keymap.set("n", "<leader>xr", "<cmd>XcodebuildBuildRun<cr>", { desc = "Build & Run Project" })
    vim.keymap.set("n", "<leader>xt", "<cmd>XcodebuildTest<cr>", { desc = "Run Tests" })
    vim.keymap.set("n", "<leader>xT", "<cmd>XcodebuildTestClass<cr>", { desc = "Run This Test Class" })
    vim.keymap.set("n", "<leader>xf", "<cmd>XcodebuildTestTarget<cr>", { desc = "Run This Test Target" })
    vim.keymap.set("n", "<leader>X", "<cmd>XcodebuildPicker<cr>", { desc = "Show All Xcodebuild Actions" })
    vim.keymap.set("n", "<leader>xD", "<cmd>XcodebuildSelectDevice<cr>", { desc = "Select Device" })
    vim.keymap.set("n", "<leader>xp", "<cmd>XcodebuildSelectTestPlan<cr>", { desc = "Select Test Plan" })
    vim.keymap.set("n", "<leader>xs", "<cmd>XcodebuildFailingSnapshots<cr>", { desc = "Show Failing Snapshots" })
    vim.keymap.set("n", "<leader>xc", "<cmd>XcodebuildToggleCodeCoverage<cr>", { desc = "Toggle Code Coverage" })
    vim.keymap.set("n", "<leader>xC", "<cmd>XcodebuildShowCodeCoverageReport<cr>", { desc = "Show Code Coverage Report" })
    vim.keymap.set("n", "[r", "<cmd>XcodebuildJumpToPrevCoverage<cr>", { desc = "Jump To Previous Coverage" })
    vim.keymap.set("n", "]r", "<cmd>XcodebuildJumpToNextCoverage<cr>", { desc = "Jump To Next Coverage" })
    vim.keymap.set("n", "<leader>xq", "<cmd>Telescope quickfix<cr>", { desc = "Show QuickFix List" })

    vim.keymap.set("n", "<D-b>", "<cmd>XcodebuildBuild<cr>", { desc = "Build Project" })
    vim.keymap.set("n", "<D-r>", xcodebuild.build_and_debug, { desc = "Build & Debug" })
    -- vim.keymap.set("n", "<D-r>", "<cmd>XcodebuildBuildRun<cr>", { desc = "Build & Run Project" })
    vim.keymap.set("n", "<D-u>", "<cmd>XcodebuildTest<cr>", { desc = "Run Tests" })
  end,
}
```

**Comment by wojciech-kulik** [comment]
Hmm, your config looks ok, but you are missing one dependency. Try adding: `MunifTanjim/nui.nvim` and let me know if it helps.

**Comment by wojciech-kulik** [comment]
Also it looks like you are missing something here: 
<img width="753" alt="image" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/3128467/23f44683-b3b6-45bd-836d-152f97faa67a">
I don't see `xcodebuild` defined here. I guess you are referring to `require("xcodebuild.dap")` module here.

**Comment by humblehacker** [comment]
That was it! Thanks 😄 

And thanks for all your hard work on this - this plugin is indispensable!

**Comment by humblehacker** [comment]
> Also it looks like you are missing something here: <img alt="image" width="753" src="https://private-user-images.githubusercontent.com/3128467/301676721-23f44683-b3b6-45bd-836d-152f97faa67a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MzA4OTYsIm5iZiI6MTcwNjgzMDU5NiwicGF0aCI6Ii8zMTI4NDY3LzMwMTY3NjcyMS0yM2Y0NDY4My1iM2I2LTQ1YmQtODM2ZC0xNTJmOTdmYWE2N2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjMzNjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmIwNjJhMzM3NjZhOTk4ODNlOWM0YmVmMGIxMzYwZTU5YmQwM2Y3MDkzODJhZmYxZTI0YWJkNDNhMDU3MGI3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OgjJpG6hd_5dE5yWOheLklhDPCOBGdNxtzl866mWd4Q"> I don't see `xcodebuild` defined here. I guess you are referring to `require("xcodebuild.dap")` module here.

Good catch. I was wondering why that key had stopped working, but I hadn't bothered to look yet. Copy/paste issue. I replaced my original mappings with some I copied from somewhere else, and accidentally overwrote the require statement.

**Comment by wojciech-kulik** [comment]
> And thanks for all your hard work on this - this plugin is indispensable!

Great to hear! And I'm glad I was able to help 🍻
