### ISSUE TITLE
[Trick] debug view hirearchy

### ISSUE THREAD

**Issue by iMostfa** [wojciech-kulik/xcodebuild.nvim#213]
Hi, 

https://github.com/user-attachments/assets/2899f9c4-f4f1-4026-9efb-7dd7b007a5f9

i found that i need to open Xcode to debug the views from time to time. which is something i hate -opening Xcode-

so i tried to found an alternative and ended up using revealapp.com

and i managed to integrate it in my config, i share this with you, so we can decide if it's worth it to be added inside the tips/tricks section ? or no. 

the steps are like this: 
1- load reveal into lldb when it's initilized (this's needed because Codelldb doesn't appear to check the global `~/.lldb` file)
2- set a breakpoint on `UIApplicationMain` (when codeLLDB) is initilized

3- then on `event_stopped` i check if we didn't setup Reveal, then i setup it by calling `reveal load --autostart` and then i continue the breakpoint.

the only downside of this approach that the code will switch to the assembly at the breakpoint, but it's not a big deal for me (given that i really need to debug my views without opening Xcode) 

also, Reveal isn't free :/ 

```lua

  local didLoadReveal = false
  dap.listeners.after["event_stopped"]["me"] = function()
    if not didLoadReveal then
      didLoadReveal = true
      dap.repl.execute("reveal load --autostart")
      vim.defer_fn(function()
        dap.continue()
      end, 1000)
    end
  end
  dap.listeners.after["event_initialized"]["me"] = function()
    if not areSet then
      areSet = true
      dap.repl.execute(
        "command script import /Users/mostafa.essam/Library/Application\\ Support/Reveal/RevealLLDBCommands/reveallldb")
      dap.repl.execute(
        "breakpoint set -F UIApplicationMain -L objc")
    end
  end


```

**Comment by iMostfa** [comment]
@wojciech-kulik i tried to find a way to trigger Xcode's view hierarchy but i found nothing :/

**Comment by wojciech-kulik** [comment]
I linked this issue in Wiki: https://github.com/wojciech-kulik/xcodebuild.nvim/wiki/Tips-&-Tricks#view-hierarchy

Thanks for sharing!

**Comment by soundsmitten** [comment]
This looks promising https://lookin.work/

**Comment by wojciech-kulik** [comment]
I haven't tested it yet, but looks really cool! Thanks for sharing 🔥
