### ISSUE TITLE
`Could not detect test target. Please run build for testing`

### ISSUE THREAD

**Issue by bengidev** [wojciech-kulik/xcodebuild.nvim#22]
Hello, i want to try to run testing from NeoVim with `xcodebuild.nvim`, and i think the tests not works as expected. This is the errors when i run the tests using command from `xcodebuild.nvim`.
![Screenshot 2024-02-11 at 11 46 55](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/c811c414-e9a7-4239-9ce9-fdfc38db4756)

- This is my `xcodebuild.nvim`:
![Screenshot 2024-02-11 at 11 49 20](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/b3a9a8c4-f6c6-48ac-bdde-8c1dd2711ee0)

- This is my default test:
![Screenshot 2024-02-11 at 11 45 50](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/2164b1c7-6945-4a4b-92d6-83de7b070787)

- I try to `Build for Testing` first:
![Screenshot 2024-02-11 at 11 46 08](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/0dfb2ad5-8e7a-43d1-8ddf-7a48ff327441)

- This is the `build` result:
![Screenshot 2024-02-11 at 11 46 34](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/8b07887b-6aa1-4d3a-9805-172ea03ae5a9)

- I try to run the tests:
![Screenshot 2024-02-11 at 11 46 49](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/475693c2-f790-4411-be6d-a1a8011f6975)

- And this is the results:
![Screenshot 2024-02-11 at 11 46 55](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/48014755/9b9acda3-f91e-483b-b382-163a1ff1836d)

**Comment by bengidev** [comment]
- This is my `settings.json`:
`{"projectCommand": "-project '/Users/beng/Documents/iOS App Developer/Space_News_SwiftUI/Space News/Space News.xcodeproj'", "os": "17.2", "productName": "Space News", "bundleId": "com.github.bengidev.Space-News", "appPath": "/Users/beng/Library/Developer/Xcode/DerivedData/Space_News-gxwsdsmwuavqvtfajndbcoiytezs/Build/Products/Debug-iphonesimulator/Space News.app", "xcodeproj": "/Users/beng/Documents/iOS App Developer/Space_News_SwiftUI/Space News/Space News.xcodeproj", "lastBuildTime": 6, "deviceName": "iPhone 15 Pro", "platform": "iOS Simulator", "destination": "9008A034-3255-4387-BAC6-2DF310780AF9", "projectFile": "/Users/beng/Documents/iOS App Developer/Space_News_SwiftUI/Space News/Space News.xcodeproj", "testPlan": "Space News", "config": "Debug", "scheme": "Space News"}`

**Comment by wojciech-kulik** [comment]
I assume that the case above was the root cause of the problem. In case the problem still occurs please reopen this issue.
