### ISSUE TITLE
Support for regular tests in a scheme without test plans

### ISSUE THREAD

**Issue by iMostfa** [wojciech-kulik/xcodebuild.nvim#241]
Hi, 

i see that i need to have `Test plan` to be able to run tests, is it possible/easy to work without test plans ?

**Comment by wojciech-kulik** [comment]
Is it some old project? Currently, new projects already have an auto-generated test plan.

Could you create a sample project that doesn't have a test plan? I can't do it on my side.

**Comment by iMostfa** [comment]
Yes, it's an old project, i will try to make one and mention you today

**Comment by iMostfa** [comment]
i invited you to a private project that you can check to see the problem

**Comment by iMostfa** [comment]
<img width="747" alt="Screenshot 2024-11-15 at 15 56 38" src="https://github.com/user-attachments/assets/a2492310-1d9c-4870-b07a-c0198234ec9d">

for this project, tests won't appear in nvim unless i tap on convert to test plans

**Comment by wojciech-kulik** [comment]
> i invited you to a private project that you can check to see the problem

Thanks, I will check it.

Btw. why don't you want to migrate to Test Plans :D?

**Comment by notlus** [comment]
I tried this out on an old project with no test plan and I get this error:
"The flag -testPlan <name> cannot be used since the scheme does not use test plans."

If I comment these lines out in the `command` table, it works:
```
    opts.testPlan and "-testPlan" or nil,
    opts.testPlan,
```

**Comment by wojciech-kulik** [comment]
Hmm, so it looks like your `testPlan` is not empty in the config? Check out the current configuration.

**Comment by wojciech-kulik** [comment]
I'm not sure how it happened that your testPlan is set to `""` by analyzing the code the only option I see is that the list of test plans returned empty lines and you selected one of them? Could you try running the configuration wizard and check what happens on test plans step?

**Comment by wojciech-kulik** [comment]
Could you check what is set in `testPlan` field in:
``` 
/your/path/.nvim/xcodebuild/settings.json
```

**Comment by notlus** [comment]
> I'm not sure how it happened that your testPlan is set to `""` by analyzing the code the only option I see is that the list of test plans returned empty lines and you selected one of them? Could you try running the configuration wizard and check what happens on test plans step?

The configuration does show a test plan, but it is not for the project. It is a test plan for a local Swift package dependency.

**Comment by wojciech-kulik** [comment]
Oh, I see what happened most likely. I see that the code doesn't set `testPlan` to `nil` if it's not detected. So probably before you were switching to your package, it set the test plan and now when you switched back to another project it stayed there.

**Comment by notlus** [comment]
I have not switched to that package in a while and have run the configuration wizard since doing that. Would that still  be the case?

**Comment by wojciech-kulik** [comment]
Yes, because if the test plan is not detected it was not changed to `nil` so the value from the previously selected project remained. I just fixed that, download the latest version, rerun the wizard, and see if the problem is fixed :)

**Comment by notlus** [comment]
With that change I can run the tests successfully.

One other issue is that although the logs show that all of the tests were run, only a small subset of the tests show up in the test explorer. Additionally, tests from that Swift package scheme are present, but do correctly show they were not run.

**Comment by wojciech-kulik** [comment]
Could you provide your logs? The plugin builds Test Explorer based on logs, I would need to see where the parser fails. You could obfuscate test names if they contain some work-related things and it doesn't require too much effort.

Regarding Swift package tests, maybe they also remained from your previous configuration, you can clear Test Explorer by using `X` inside.

**Comment by notlus** [comment]
Here is the logs from running  the test:

Resolving Package Graph
[!]  --- xcodebuild: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006020-00062160267B401E, name:My Mac }
{ platform:macOS, arch:x86_64, id:00006020-00062160267B401E, name:My Mac }
Resolved source packages
swift-log - https://github.com/apple/swift-log.git @ 1.6.1
CocoaLumberjack - https://github.com/CocoaLumberjack/CocoaLumberjack.git @ 3.8.1
swift-argument-parser - https://github.com/apple/swift-argument-parser @ 1.4.0
Selected tests
AllTests.xctest
FirstTests
    ✔ testEC
    ✔ testAC (0.001 seconds)
    ✔ testANSITime (0.001 seconds)
    ✔ testApplicationDocumentsDirectory (0.001 seconds)
    ✔ testAttribsForPath (0.009 seconds)
    ✔ testBPFE (0.000 seconds)
    ✔ testChecksums (0.016 seconds)
    ✔ testContainingFolder (0.000 seconds)
    ✔ testCHF
    ✔ testSN (0.013 seconds)
    ✔ testPlistForBundle (0.056 seconds)
    ✔ testEB (0.000 seconds)
    ✔ testEL (0.000 seconds)
    ✔ testExecutable (0.015 seconds)
    ✔ testExtensionOfPath (0.000 seconds)
    ✔ testH (0.024 seconds)
    ✔ testflagsForPath (0.881 seconds)
    ✔ testFU (0.213 seconds)
    ✔ testGU (0.004 seconds)
    ✔ testGetBundleIdentifier (0.001 seconds)
    ✔ testGetCurrentUsername (0.000 seconds)
    ✔ testGetIPAddress (0.001 seconds)
    ✔ testGetIPAddresses (0.076 seconds)
    ✔ testGetMACAddress (0.004 seconds)
    ✔ testGetUserHomeDirectory (0.001 seconds)
    ✔ testIPB (0.007 seconds)
    ✔ testIII (0.007 seconds)
    ✔ testIsFileExecutable (0.003 seconds)
    ✔ testIsPathInTrash (0.000 seconds)
    ✔ testIsP (0.001 seconds)
    ✔ testIsS (0.001 seconds)
    ✔ testIsSP (0.000 seconds)
    ✔ testIsTempFolderPath (0.000 seconds)
    ✔ testCommandStringForPID (0.001 seconds)
    ✔ testNameFromPath (0.000 seconds)
    ✔ testOSVersionString (0.001 seconds)
    ✔ testOOP (0.001 seconds)
    ✔ testPID (0.001 seconds)
    ✔ testO(0.001 seconds)
    ✔ testSize (0.001 seconds)
    ✔ testStatic (0.011 seconds)
    ✔ testIdleTime (0.001 seconds)
    ✔ testVolume (0.474 seconds)
    ✔ testTimestamp (0.000 seconds)
    ✔ testBadUUID (0.210 seconds)
    ✔ testVN (0.002 seconds)
Executed 46 tests, with 0 failures (0 unexpected) in 2.040 (2.051) seconds
SecondTests
    ✔ testLoopback (0.018 seconds)
    ✔ testAPIServer (0.001 seconds)
Executed 3 tests, with 0 failures (0 unexpected) in 0.048 (0.048) seconds
ThirdTests
    ✔ testCredentials (0.013 seconds)
Executed 1 test, with 0 failures (0 unexpected) in 0.013 (0.013) seconds
FourthTests
    ✔ test_compUSW_credentials (0.001 seconds)
    ✔ test_compUSW_emptyCredentials (0.001 seconds)
    ✔ test_compUSW_emptyHost (0.001 seconds)
    ✔ test_compUSW_emptyScheme (0.001 seconds)
    ✔ test_compUSW_invalidHost (0.001 seconds)
    ✔ test_compUSW_negativePort (0.001 seconds)
    ✔ test_compUSW_nilCredentials (0.000 seconds)
    ✔ test_compUSW_onlyPasswordCred (0.000 seconds)
    ✔ test_compUSW_onlyUserCred (0.008 seconds)
    ✔ test_compUSW_specialCharactersInCredentials (0.000 seconds)
    ✔ test_compUSW_zeroPort (0.001 seconds)
Executed 11 tests, with 0 failures (0 unexpected) in 0.014 (0.016) seconds
FifthTests
    ✔ testReadWrite (35.104 seconds)
Executed 1 test, with 0 failures (0 unexpected) in 35.104 (35.105) seconds
SixthTests
    ✔ testDataReadWrite (0.062 seconds)
    ✔ testDictionaryReadWrite (0.048 seconds)
    ✔ testEmptyDictionaryReadWrite (0.047 seconds)
    ✔ testStringReadWrite (0.051 seconds)
Executed 4 tests, with 0 failures (0 unexpected) in 0.208 (0.209) seconds
Test Suite 'AllTests.xctest' passed at 2024-11-15 12:51:30.474.
Executed 66 tests, with 0 failures (0 unexpected) in 37.426 (37.444) seconds
Executed 66 tests, with 0 failures (0 unexpected) in 37.426 (37.444) seconds
Test Execute Succeeded
Testing started

-----------------------------
-- xcodebuild.nvim summary --
-----------------------------

  ✔ All Tests Passed [Executed: 66]

**Comment by iMostfa** [comment]
```Errors:
  ✖ The flag -testPlan <name> cannot be used since the scheme does not use test plans.

  Build Failed
```
for the project i attached to you it worked, for another project, i got this error, do have any clue ☹️

**Comment by notlus** [comment]
> ```
>   ✖ The flag -testPlan <name> cannot be used since the scheme does not use test plans.
> 
>   Build Failed
> ```
> 
> for the project i attached to you it worked, for another project, i got this error, do have any clue ☹️

@iMostfa I had the same issue and @wojciech-kulik made a fix that addressed it for me. Make sure you pull the latest version plugin and try it.
