### ISSUE TITLE
Error upon NVim launch

### ISSUE THREAD

**Issue by KRUBERLICK** [wojciech-kulik/xcodebuild.nvim#242]
Upon launching NVim the following error message pops up and I'm unable to build the project:

<img width="876" alt="image" src="https://github.com/user-attachments/assets/bb4d744e-c717-408e-8e2e-f16e3c1ca893">

Any info on what could it be? Thanks!

**Comment by wojciech-kulik** [comment]
Hi! Thanks for reporting that! The code verifying if `fd` tool is installed was invalid. I fixed that :).

**Comment by KRUBERLICK** [comment]
Much thanks!
