### ISSUE TITLE
Unable to build Xcode project that was generated by CMake

### ISSUE THREAD

**Issue by notlus** [wojciech-kulik/xcodebuild.nvim#253]
The project is [here](https://github.com/Hyland/DocumentFilters) and requires CMake to build.

To reproduce do the following:
- `git clone https://github.com/Hyland/DocumentFilters`
- `cd DocumentFilters`
- run `cmake -G "Xcode" .`, which generates an Xcode project
- Run the xcodebuild configuration wizard, which appears to succeed
- Attempt to build a scheme

Following the above I get a "The project is missing some details" error. The project builds fine in Xcode.

I have narrowed it down to the settings.json missing the "productName", "appPath" and "bundleId" keys. If I manually add them, then the build works as expected. I believe the project has static and dylib targets that don't define a bundle ID and don't have an app.

**Comment by wojciech-kulik** [comment]
It seems like it requires adding support for static libraries. As you mentioned, as a workaround, you can add those 3 values to `settings.json`. They are used only to run/debug the app which is not available for static libraries anyway.

**Comment by wojciech-kulik** [comment]
I added support for static library :) Now it should work as expected. Just run the wizard again.
