### ISSUE TITLE
install command no longer supports the `-D` option

### ISSUE THREAD

**Issue by mjKosmic** [wojciech-kulik/xcodebuild.nvim#254]
When installing the `remote_debugger` script for debugging with `pymobiledevice3`, the script shown when using `:help xcodebuild.remote-debugger` doesn't work as written. the `install` command no longer has a `-D` flag for creating parent directories on the destination

**Comment by mjKosmic** [comment]
doing this worked for me 

`DEST="$HOME/Library/xcodebuild.nvim/remote_debugger" && \
    SOURCE="$HOME/.local/share/nvim/lazy/xcodebuild.nvim/tools/remote_debugger" && \
    ME="$(whoami)" && \
    sudo install -d -m 755 -o root "$DEST" && \
    sudo install -m 755 -o root "$SOURCE" "$DEST" && \
    sudo bash -c "echo \"$ME ALL = (ALL) NOPASSWD: $DEST\" >> /etc/sudoers"
`

**Comment by mjKosmic** [comment]
I'm on Sonoma
<img width="812" alt="Screenshot 2024-11-24 at 3 10 05 PM" src="https://github.com/user-attachments/assets/eeefe66e-6c39-4361-9481-1f8373b5866a">

**Comment by wojciech-kulik** [comment]
You are right, `-D` is not available prior to Sequoia. I updated the documentation to make it work without `-D`. 

Thank you for reporting this problem!
