### ISSUE TITLE
Could not install app (code: 2)

### ISSUE THREAD

**Issue by EastHell** [wojciech-kulik/xcodebuild.nvim#39]
I had an error from title `Could not install app (code: 2)` after success building.

After research a little, I found that error occurs due to wrong `productName` detection. In **xcode.lua** file, inside `M.get_build_settings` function. For some reason in my case actual app name inside build directory is not in `PRODUCT_NAME` setting key, but in `PRODUCT_MODULE_NAME` key. After switching it works great. So is id depends on something? Because in my case actual app name contains cyrylic symobls.

Also exactly `PRODUCT_MODULE_NAME` used in `EXECUTABLE_NAME` key.

**Comment by wojciech-kulik** [comment]
Hi, thank you for reporting the problem. Could you first provide some information about your project?

1. What Xcode do you use?
2. What macOS do you use?
3. How is your project structured? Does it have multiple targets? Does it use SPM packages? 
4. Could you show your build settings of your main target? Select Customized + Combined
5. Could you show your xcodebuild.nvim settings? `.nvim/xcodebuild/settings.json` (before your fix)
6. Could you show the list of files from `DerivedData/YourApp/Build/Products/Debug-iohonesimulator`?
7. Could you show the list of files from `DerivedData/YourApp/Build/Products/Debug-iohonesimulator/YourApp.app`?
8. Do you use xcodegen or Tuist or any other tool to generate the project file?
9. What is your Xcode project format? You can check it here, after selecting the main project in the file tree:
<img width="265" alt="image" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/3128467/d80348c2-6a2e-469a-b70a-0b9fc49deb4d">

**Comment by EastHell** [comment]
1. `Xcode 15.2.0 via Xcodes`
2. `Mac OS Sonoma 14.2.1`
3. Actually pretty default structure. App target, few tests targets, notification targets and widget extension. Multiple SPM packages.
4. I'm not sure, there's might be a lot of NDA information. But i can display some valuable settings by hands.
```
Info.plist Values:
  Bundle Display Name: CyrilycName

Packaging:
  Product Module Name: App
  Product Name: CyrilycName

User-Defined:
  EXECUTABLE_NAME: App
  WRAPPER_NAME: App.app
```
5.  `.nvim/xcodebuild/settings.json` before fix
```
{"platform": "iOS Simulator", "productName": "CyrilycName", "projectFile": "/Users/user/Developer/project/App/App.xcodeproj", "config": "Debug", "os": "15.5", "xcodeproj": "/Users/user/Developer/project/App/App.xcodeproj", "deviceName": "iPhone 13 Pro", "appPath": "/Users/user/Library/Developer/Xcode/DerivedData/App-ggihzwjwnmuqruhedfvixwzbiktz/Build/Products/Debug-iphonesimulator/CyrilycName.app", "destination": "25B49FFF-6F40-45B4-A537-2C9BF9CF607E", "bundleId": "com.name.mobile.test", "scheme": "App", "projectCommand": "-project '/Users/user/Developer/project/App/App.xcodeproj'", "lastBuildTime": 14}
```
6. Because of NDA cant show full list, but most important that instead of 
`/Users/user/Library/Developer/Xcode/DerivedData/App-ggihzwjwnmuqruhedfvixwzbiktz/Build/Products/Debug-iphonesimulator/CyrilycName.app`
here is 
`/Users/user/Library/Developer/Xcode/DerivedData/App-ggihzwjwnmuqruhedfvixwzbiktz/Build/Products/Debug-iphonesimulator/App.app` 
so actually exactly this difference causing a problem
7. Inside 
`/Users/user/Library/Developer/Xcode/DerivedData/App-ggihzwjwnmuqruhedfvixwzbiktz/Build/Products/Debug-iphonesimulator/App.app`
there's also executable with name `App`
8. No, I don't use any project generation tools.
9. 
<img width="258" alt="image" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/28960974/7045a0f5-8758-43cd-93cc-c5b49bd68ebe">

**Comment by wojciech-kulik** [comment]
Thank you for the detailed information!

So I think you already spotted the problem:
<img width="259" alt="image" src="https://github.com/wojciech-kulik/xcodebuild.nvim/assets/3128467/556fcbe6-70ab-4fa4-a42b-caf2bb5ca547">

Basically, it overwrites the Product Name while generating the app. I will verify if I can rely on `WRAPPER_NAME`/`EXECUTABLE_NAME` instead of `PRODUCT_NAME` but I will need to perform some tests

**Comment by wojciech-kulik** [comment]
@EastHell I fixed it :). Please verify with the new version if it works as expected now.

**Comment by EastHell** [comment]
@wojciech-kulik Thank you! It works great! Also awesome plugin!
