### ISSUE TITLE
[Feature Request] Clean build folder

### ISSUE THREAD

**Issue by Almaz5200** [wojciech-kulik/xcodebuild.nvim#4]
Thanks a lot for the plugin, it's truly great, good to know I'm not alone on this path. Previously I only got autocomplete working, but now I can do most things without Xcode being even open.
It'd be great if it was possible to clean build folder using it as well

**Comment by wojciech-kulik** [comment]
Hi, thank you! 

I mentioned it on the TODO list in readme:

> Add clean build action. While testing this command was failing for some reason, that's why for now it's postponed.

I need some more testing, but in my case, `xcodebuild clean` fails for some strange reasons. Maybe connected with `build` command it will work.

**Comment by wojciech-kulik** [comment]
@Almaz5200 This issue has been resolved in b1cda730b3cc1ae04013e6e71109a1c2f9941b19. 

Download the latest version and try `XcodebuildCleanBuild` :). 
I also added an action to delete DerivedData: `XcodebuildCleanDerivedData`

At the same time I release v1.0.0, you may want to check out release notes: https://github.com/wojciech-kulik/xcodebuild.nvim/releases/tag/v1.0.0
