### ISSUE TITLE
Error when trying to make new groups or files in project

### ISSUE THREAD

**Issue by dstabr** [wojciech-kulik/xcodebuild.nvim#42]
This is updating my group in a project. In this case it was deleting a group that already didn't add to the project.

```
 /Users/douglas/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:22:in `find_group_by_absolute_dir_path': undefined method `filter_map' for #<Enumerator::Lazy:0x000000013a0f5128> (NoMethodError)
    2 Did you mean?  filter
    3         from /Users/douglas/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:110:in `delete_group'
    4         from /Users/douglas/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:170:in `handle_action'
    5         from /Users/douglas/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:199:in `<main>'
```

This is trying to create a new file in project

```
    1 /Users/douglas/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:7:in `find_group_by_absolute_file_path': undefined method `filter_map' for #<Enumerator::Lazy:0x000000011e28c638> (NoMethodError)
    2 Did you mean?  filter
    3         from /Users/douglas/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:43:in `add_file_to_targets'
    4         from /Users/douglas/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:145:in `handle_action'
    5         from /Users/douglas/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:199:in `<main>'
```

**Comment by wojciech-kulik** [comment]
What does it print out:
```
ruby --version
```

It looks like you are using an outdated ruby version. `filter_map` was introduced in ruby 2.7.0.

**Comment by dstabr** [comment]
So that ended up working updated ruby and for this issue now. Do I need to do something with Xcodeproj now. 


<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require': cannot load such file -- xcodeproj (LoadError)
	from <internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from /Users/douglas/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:1:in `<main>'

**Comment by wojciech-kulik** [comment]
It looks like you didn't install the required dependency. Please follow the instruction: https://github.com/wojciech-kulik/xcodebuild.nvim#-installation

**Comment by dstabr** [comment]
Sorry to waste your time. I reinstall the dependencies and it did start working after that.

**Comment by wojciech-kulik** [comment]
Great to hear 🎊
