### ISSUE TITLE
Passing workspace and scheme to xcodebuild

### ISSUE THREAD

**Issue by whiteio** [wojciech-kulik/xcodebuild.nvim#46]
Hi! Would it be possible to have the ability to set both the -workspace and -scheme flag when running xcodebuild?

**Comment by wojciech-kulik** [comment]
Hi! I'm not sure what you mean. Currently, both scheme and workspace/project are passed to xcodebuild commands.
Could you explain your use case?

**Comment by whiteio** [comment]
I was having an issue when using `:XcodeSetup`, once I selected the `.xcworkspace` it didn't display any build configurations to use. I was setting it up in a project which uses tuist and consists of a `.xcworkspace` and multiple `xcodeproj`'s.

I was able to get around the issue by going using `:XcodeSetup`, selecting an `.xcodeproj`, completing the rest of the steps and then using `:XcodeBuildSelectProject` to select the `.xcworkspace`. I also missed the part in the docs where it suggests editing the `settings.json` file directly, modifying it in there works for me too now.

Btw great job on making this plugin, it's amazing.

**Comment by wojciech-kulik** [comment]
Oh, I see the problem. The plugin currently supports only projects with a single `xcodeproj`. So if you select `ABC.xcworkspace`, it assumes you should also have `ABC.xcodeproj`. I think, I will need to add `xcodeproj` selection if a user selects `xcworkspace`.

> Btw great job on making this plugin, it's amazing.

Thank you! 🍻

**Comment by whiteio** [comment]
Seems to be selected automatically:
1. `Select Project/Workspace` - select `App.xcworkspace`
2. `Select Build Configuration` - it's empty

`xcodebuild -project 'PATH/TO/XYZ.xcodeproj' -list`:
```
Information about project “App”:
    Targets:
        AppTests
        AppUITests
        AppNotificationService
        App

    Build Configurations:
        Debug
        Release

    If no build configuration is specified and -scheme is not passed then "Release" is used.

    Schemes:
        App
        AppNotificationService
```

---

`xcodebuild -workspace 'PATH/TO/XYZ.xcworkspace' -list`:
```
Information about workspace “App”:
    Schemes:
        XYZScheme
        ZYXScheme
        App
        App-Workspace
        …
```

**Comment by wojciech-kulik** [comment]
Hmm, this is weird, because your output shows that it's correct and contains configurations. I assume that you run it for `xcodeproj` with the same name as your project, right?

Now, your project is configured, so if you run `:XcodebuildSelectConfig` there is still an empty list?

**Comment by whiteio** [comment]
Path to the xcworkspace is `/Users/whiteio/Dev/App-iOS/App.xcworkspace`

```
- App.xcworkspace
- App (Folder)
---- App.xcodeproj
- Folder
---- XYZ (Folder)
-------- XYZ.xcodeproj
---- ZYX (Folder)
-------- ZYX.xcodeproj
- Folder
---- XYZ123 (Folder)
-------- XYZ123.xcodeproj
---- ZYX123 (Folder)
-------- ZYX123.xcodeproj
```

After setting it up by using `:XcodebuildSetup` and selecting the xcodeproj and going through the rest of the steps, and then using `:XcodebuildSelectProject` to select the xcworkspace:
`:XcodebuildSelectConfig` - `Select build configuration` is empty

**Comment by wojciech-kulik** [comment]
Ok, so it is weird that `xcodeproj` is set automatically if it's actually in a different folder. 

Could you delete `.nvim/xcodebuild/settings.json`, run the wizard and paste here the content (of course you can obfuscate it)? And especially check `xcodeproj` path there.

**Comment by wojciech-kulik** [comment]
Thank you for your engagement with this issue, I appreciate that 🍻!

You should have a field `xcodeproj`, but it's not there. As far as I can see from code, there is no way to skip saving this field and jumping to Build Configurations. 

So I guess that you are using an old version of the plugin. Could you check at which commit you are?

**Comment by wojciech-kulik** [comment]
Great that we managed to solve it 🍻 Since then lots of new features have been added :) Check out README or Releases to be up to date.
