### ISSUE TITLE
Refreshing LSP after adding a new file?

### ISSUE THREAD

**Issue by wojciech-kulik** [wojciech-kulik/xcodebuild.nvim#56]
When you add a new file, it always shows some errors because the LSP is unable to place this file in a project structure yet. You need to build the project and usually restart LSP.

Maybe it is possible to somehow improve this process?

Ideas:
1. Run build in the background & call `xcode-builld-server parse .nvim/xcodebuild/original_logs.log -o .nvim/xcodebuild/.compile`?
2. Is there any way to force an update without building? How Xcode achieved that?
3. It could be also a limitation of `sourcekit-lsp` in their repo they say:
     ```
     SourceKit-LSP does not update its global index in the background, but instead relies on indexing-while-building to provide data. 
     This only affects global queries like find-references and jump-to-definition.
     Workaround: build the project to update the index
     ```

**Comment by Almaz5200** [comment]
I actually mapped LSP Reloading on <leader>xL for this exact purpouse

**Comment by wojciech-kulik** [comment]
I found the connected ticket: https://github.com/apple/sourcekit-lsp/issues/969. I guess it's worth to subscribe there :).

**Comment by SolaWing** [comment]
xcode-build-server normally doesn't need to restart as soon as parse logs. It will watch updated logs to send new flags to lsp.

**Comment by wojciech-kulik** [comment]
@SolaWing maybe some notification from BSP to LSP is needed to refresh diagnostics?

**Comment by SolaWing** [comment]
currently only flags changes can be notified from BSP. and if flags is current, LSP can figure out diagnostics. defs and refs seems to depend on the index-store file update

**Comment by wojciech-kulik** [comment]
ok, I will check this issue one more time and I will create an ticket for sourcekit-lsp then

**Comment by wojciech-kulik** [comment]
@SolaWing is also trying to workaround this problem directly in xcode-build-server. The issue to track: https://github.com/SolaWing/xcode-build-server/issues/43

**Comment by wojciech-kulik** [comment]
xcode-build-server v1.1.0 has been released. It should improve the workflow with new files.

In case of any issue please report it directly to: https://github.com/SolaWing/xcode-build-server
