### ISSUE TITLE
Create settings.json file failed

### ISSUE THREAD

**Issue by TMTBO** [wojciech-kulik/xcodebuild.nvim#58]
Launch neovim in a new project folder which without `settings.json` file, I got the backtrace blow. 
```
Failed to run `config` for xcodebuild.nvim

...m/lazy/xcodebuild.nvim/lua/xcodebuild/project/config.lua:42: attempt to index field 'settings' (a number value)

# stacktrace:
  - /xcodebuild.nvim/lua/xcodebuild/project/config.lua:42 _in_ **update_global_variables**
  - /xcodebuild.nvim/lua/xcodebuild/project/config.lua:57 _in_ **load_settings**
  - /xcodebuild.nvim/lua/xcodebuild/init.lua:197 _in_ **setup**
  - ~/.config/nvim/lua/plugins/plugins.lua:125 _in_ **config**
  - /rust-tools.nvim/lua/rust-tools/init.lua:124 _in_ **setup**
  - /LazyVim/lua/lazyvim/plugins/extras/lang/rust.lua:141
  - ~/.config/nvim/lua/rafi/plugins/lsp/init.lua:213
  - /mason-lspconfig.nvim/lua/mason-lspconfig/init.lua:84 _in_ **fn**
  - /mason.nvim/lua/mason-core/optional.lua:101 _in_ **if_present**
  - /mason-lspconfig.nvim/lua/mason-lspconfig/init.lua:82 _in_ **fn**
  - /mason.nvim/lua/mason-core/functional/list.lua:98 _in_ **each**
  - /mason-lspconfig.nvim/lua/mason-lspconfig/init.lua:92 _in_ **setup_handlers**
  - /mason-lspconfig.nvim/lua/mason-lspconfig/init.lua:50 _in_ **setup**
  - ~/.config/nvim/lua/rafi/plugins/lsp/init.lua:258 _in_ **config**
  - vim/_editor.lua:0 _in_ **cmd**
  - /persistence.nvim/lua/persistence/init.lua:79 _in_ **load**
  - ~/.config/nvim/lua/rafi/plugins/editor.lua:94
  ```

**Comment by TMTBO** [comment]
![image](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/2801001/6e2da5d4-0af6-43be-b667-c74127d10e1b)

**Comment by wojciech-kulik** [comment]
Thank you for the information! And when the error occurs? Based on stack trace I guess on Neovim start? Have you called `:XcodebuildSetup` to configure the project?

If configuring the project doesn’t help. You can try temporarly creating the settings file manually. Check out the bottom of the README to find an example.

In general, based on the stack trace the code shoudl’t reach this place if `.nvim/xcodebuild/settings.json` doesn`t exist. Will need to investigate that.

**Comment by wojciech-kulik** [comment]
I’m unavailable this week, but if anyone wants to take a look, [this line](https://github.com/wojciech-kulik/xcodebuild.nvim/blob/df0641e68ded399fb02ed30eb2fa97f41592fe75/lua/xcodebuild/project/config.lua#L53) should prevent the code from reaching the `update_global_variables` from the stack trace. 

So I’m not sure how it happend. Maybe in some cases `pcall` can succeed even if the file doesn`t exist?

**Comment by wojciech-kulik** [comment]
@TMTBO what Neovim version do you use?

**Comment by TMTBO** [comment]
> @TMTBO what Neovim version do you use?

▶ nvim -v
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"

Run :checkhealth for more info

**Comment by TMTBO** [comment]
#61 I made a PR. Please take a look at that when you are available.

**Comment by wojciech-kulik** [comment]
I think I can accept it. Based on the code it shouldn’t break anything. I guess you tested it and it resolves your issue?

**Comment by TMTBO** [comment]
> I think I can accept it. Based on the code it shouldn’t break anything. I guess you tested it and it resolves your issue?

Yes, it resolves my issue!

**Comment by wojciech-kulik** [comment]
It looks like the problem is deeper: https://www.reddit.com/r/neovim/comments/1b5iibt/comment/kt7ot3j/?context=3

Will need to investigate it.

**Comment by TMTBO** [comment]
Oh, that's terrible.

**Comment by TMTBO** [comment]
It works now! Thanks you very much!
