### ISSUE TITLE
Initial :XcodebuildSetup stuck "loading project information..."

### ISSUE THREAD

**Issue by egradman-red6ar** [wojciech-kulik/xcodebuild.nvim#62]
Hi, I created a new Xcode 15.3 project for VisionOS from the app template.  Opened the root directory in nvim and ran `:XcodebuildSetup` and selected the `.xcodeproj` file.  The bottom bar is stuck saying "Loading project information..."

If there's any progress debug output, I don't know where to find it.

Thanks for making this!

**Comment by wojciech-kulik** [comment]
Hi! Xcode 15.3 is not yet released, so I guess, you keep it on the side? This plugin runs `xcodebuild` and `xcrun` commands, so I guess you need to change your current command line tools.

You can either do it from Xcode or using command line.

To check current path:
```
xcode-select --print-path
```

To change it:
```
xcode-select --switch
```

Let me know if it helped :)

**Comment by wojciech-kulik** [comment]
@egradman-red6ar could you provide more details?

**Comment by wojciech-kulik** [comment]
I'm closing the issue because of missing information. Feel free to reopen it, if the issue still occurs.
