### ISSUE TITLE
Failed Snapshot breaks if there is more than one snapshot being created within the test

### ISSUE THREAD

**Issue by Almaz5200** [wojciech-kulik/xcodebuild.nvim#8]
I've already fixed this issue in PR to relevant repo: https://github.com/wojciech-kulik/XCTestHTMLReport/pull/1

Just decided to create an issue here for anyone else facing this to see :)

**Comment by wojciech-kulik** [comment]
Oh! Nicely spotted! Thank you for resolving this issue. I will fix that on the plugin side as well.

**Comment by Almaz5200** [comment]
Yep, multiple failed asserts work and I can see both failed snapshots in navigator! Thank you so much for making iOS Development a better place :)
