### ISSUE TITLE
SourceKitLSP crash often

### ISSUE THREAD

**Issue by haoyuan80s** [wojciech-kulik/xcodebuild.nvim#85]
Hi, after setting up the package, my SourceKitLSP crash very often with error (from LspLog):
```bash
/AppleInternal/Library/BuildRoots/860631e9-c1c5-11ee-98ee-b6ef2fd8d87b/Library/Caches/com.apple.xbs/Sources/SourceKitLSP/dependencies/swift-syntax/Sources/SwiftParser/Lexer/Cursor.swift:620: Fatal error\n
```
Then, I need quit and restart nvim. Here is my lspconfig:
```lua
lspconfig.sourcekit.setup({
  cmd = {
    "xcrun",
    "--toolchain",
    "swift",
    "sourcekit-lsp",
  },
  filetypes = { "swift" },
  root_dir = function(filename, _)
    local util = require("lspconfig.util")
    return util.root_pattern("buildServer.json")(filename)
        or util.root_pattern("*.xcodeproj", "*.xcworkspace")(filename)
        or util.find_git_ancestor(filename)
        or util.root_pattern("Package.swift")(filename)
  end,
  capabilities = capabilities,
  settings = {
    sourcekit = {
      enableSyntaxMap = true,
      enableSemanticHighlighting = true,
      completion = {
        enableSnippets = true,
      },
      diagnostic = {
        enableExperimental = true,
      },
    },
  },
})
```
Any idea how to fix? Thank you!

**Comment by wojciech-kulik** [comment]
Have you tried this config:
https://github.com/wojciech-kulik/ios-dev-starter-nvim/blob/main/lua/starter/plugins/nvim-lspconfig.lua
?

**Comment by haoyuan80s** [comment]
OK, let me try. I don't have a reliable way to reproduce the error. I will use this config for a while and report :)

**Comment by wojciech-kulik** [comment]
@haoyuan80s did you have this issue again?

**Comment by haoyuan80s** [comment]
Not again. I was not writing swift intensively in these two days. It often appears during many build/rebuild debugs. Feel free to close the issue. I don't think is the xcodebuild's problem. Thank you!

**Comment by wojciech-kulik** [comment]
Sure, if it happens again, feel free to reopen it :)

**Comment by Almaz5200** [comment]
Hey! It started happening to me too, 99% of the time is when I accept CMP's suggestion, doesn't seem to matter that the source of suggestion is. What info can I provide to make it clear why that happens?

**Comment by wojciech-kulik** [comment]
Hi! This issue is unrelated with this plugin, so it would be best to open a ticket in sourcekit-lsp repo.

Also, we are having a similar discussion here: https://github.com/SolaWing/xcode-build-server/issues/43

**Comment by Almaz5200** [comment]
Got it, thanks!
