### ISSUE TITLE
Got some unexcepted chars in original_logs.log

### ISSUE THREAD

**Issue by TMTBO** [wojciech-kulik/xcodebuild.nvim#90]
Hi bro, thanks for you Excellent work. I got some problems now.
After my build project, LSP not works. And I found `.compile` file is empty.
Then I parse my xcodebuild log with the command below and got UnicodeDecodeError.  And I found some unexcepted chars appear in the log file.
When I build with `xcodebuild`, the chars disappears.
I have no idea about that, any suggestion for this?

` xcode-build-server parse .nvim/xcodebuild/original_logs.log -o .nvim/xcodebuild/.compile`

![image](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/2801001/c55f1d3c-e97f-4b94-8987-b4432d1c866c)

![image](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/2801001/30fc0a0d-85c9-49c5-b43e-41e7c1ad947c)
[original_logs.log](https://github.com/wojciech-kulik/xcodebuild.nvim/files/14596450/original_logs.log)

`xcodebuild -workspace xxx.xcodeproj -scheme xxx -configuration Debug > build.log`
[build.log](https://github.com/wojciech-kulik/xcodebuild.nvim/files/14596454/build.log)

**Comment by wojciech-kulik** [comment]
If you manually run `xcodebuild` you don't have this character in logs?

**Comment by wojciech-kulik** [comment]
@TMTBO Could you switch to [this](https://github.com/wojciech-kulik/xcodebuild.nvim/pull/91) branch and confirm if it resolves your issue?

**Comment by wojciech-kulik** [comment]
Btw. why do you need to run `xcode-build-server parse`?

**Comment by TMTBO** [comment]
Something about `Why I need to run xcode-build-server parse`:
Because I run `Build Project (Clean Build)` with `xcodebuild.nvim`, I cannot get LSP works. And I found that I donnot have a `.compile` file under `.nvim/xcodebuild` folder. So I run `xcode-build-server parse` and got  the error above.

With the new branch, `xcode-build-server parse` can generate `.compile` file and LSP works perfectly.
But `Build Project (Clean Build)` still cannot generate `.compile` file automaticly.

**Comment by TMTBO** [comment]
Thank you very much. I never knows that before. I always think that `xcode-build-server` only works with `.compile` file which just like `clangd` work with `compile_commands.json`.

**Comment by TMTBO** [comment]
On another larger project, I encountered a new problem.
The `original_logs.log` said `** BUILD SUCCEEDED **`. But the `xcodebuild.log` said ` Build Failed`. It is actually compiled successfully, and there are compiled app files in the product directory. And it worked fine for me with Xcode.

**Comment by wojciech-kulik** [comment]
The plugin prints failed build when there is any error detected. Can you search `original_logs` logs for `error: ` phrase?

**Comment by TMTBO** [comment]
![image](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/2801001/2bac5468-6fb0-453b-b93b-2f2fab82a664)
![image](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/2801001/ed5a7d5b-7cbf-4d28-aaf3-3a32e58a68a0)
![image](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/2801001/ccc92365-4b86-41e3-a7dd-2e0e84bfb04d)
![image](https://github.com/wojciech-kulik/xcodebuild.nvim/assets/2801001/6dc40cfb-b16d-4d2f-b7f4-f248e896a374)
Yes, there are some `fatal error` in the logs. It doesn't seem to affect compilation results.

**Comment by wojciech-kulik** [comment]
Weird that the build passes with fatal errors :D. Maybe try resolving this issue?

**Comment by TMTBO** [comment]
Okay, that's all right. I'll check it out later. Thanks.

**Comment by wojciech-kulik** [comment]
I'm closing this ticket, as the initial issue has been resolved. If needed please create a new ticket.
